const mongoose = require('mongoose');

const itinerarySchema = new mongoose.Schema({
  // connect this itinerary to the user who created it
  user: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true 
  },
  // file path or url of the uploaded ticket/document
  documentUrl: {
    type: String, 
    default: ''
  },
  // raw json data extracted from the ticket (flight info, dates, etc.)
  extractedData: {
    type: Object, 
    required: true
  },
  // final day-by-day travel plan generated by gemini
  generatedItinerary: {
    type: Object, 
    required: true
  },
  // toggle to control public access for sharing feature
  isShareable: {
    type: Boolean,
    default: true
  }
}, {
  timestamps: true // tracks when the itinerary was created or updated
});

module.exports = mongoose.model('Itinerary', itinerarySchema);